version: '3.8'
services:
  auth-service:
    container_name: auth-service
    image: auth-service:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - db-service
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-service/statistics_db_test

  db-service:
    #    image: postgres:14.7-alpine
    container_name: db-service
    image: db-service:0.0.1
    build:
      context: src/main/resources/db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statistics_db_test
    ports:
      - "15432:5432"
    restart: unless-stopped